// examples/nextjs/app/components/AvatarDemo.tsx
"use client"

import { useEffect, useState, useCallback } from "react"
import { useAvatar } from "@mymosdk/avatar/react"
import type { AvatarPosition, AvatarFraming, AvatarTheme } from "@mymosdk/avatar"

// ── Constants ─────────────────────────────────────────────────────────────────

const INITIAL_FRAMING: AvatarFraming = "full"
const INITIAL_THEME: AvatarTheme = "dark"

const FRAMING_CONFIG = {
  full: { from: 0.00, lookBias: 0.50 },
  half: { from: 0.48, lookBias: 0.60 },
  bust: { from: 0.60, lookBias: 0.70 },
  face: { from: 0.76, lookBias: 0.58 },
}

const THEME_CONFIG = {
  dark:  { color1: "#2a2a4a", color2: "#0d0d1a", shadowOpacity: 0.5  },
  light: { color1: "#f8f8ff", color2: "#e0e0f0", shadowOpacity: 0.15 },
}

// ── Helpers ───────────────────────────────────────────────────────────────────

async function loadDemoAudio(): Promise<AudioBuffer> {
  const ctx = new AudioContext()
  // Same CORS rule applies: use a local file or a CORS-enabled CDN URL in production.
  const response = await fetch("/demo_voice_example.mp3")
  const arrayBuffer = await response.arrayBuffer()
  return ctx.decodeAudioData(arrayBuffer)
}

type ThemeMode = "dark" | "light"
type ThemeSlices = typeof THEME_CONFIG

function buildThemeCss(mode: ThemeMode, slices: ThemeSlices) {
  const { color1, color2, shadowOpacity } = slices[mode]
  const ringOpacity = mode === "dark" ? 0.08 : 0.06
  const ringColor   = mode === "dark" ? "255,255,255" : "0,0,0"
  return {
    background: `radial-gradient(circle at 40% 35%, ${color1} 0%, ${color2} 100%)`,
    boxShadow:  `0 8px 32px rgba(0,0,0,${shadowOpacity}), 0 0 0 2px rgba(${ringColor},${ringOpacity})`,
  }
}

// ── TTS helpers ───────────────────────────────────────────────────────────────

const ELEVENLABS_DEFAULT_VOICE = "21m00Tcm4TlvDq8ikWAM"

async function fetchTTSAudio(provider: string, apiKey: string, voice: string, text: string): Promise<ArrayBuffer> {
  if (!apiKey.trim()) throw new Error("Paste your API key first")
  if (provider === "openai") {
    const res = await fetch("https://api.openai.com/v1/audio/speech", {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({ model: "tts-1", voice, input: text }),
    })
    if (!res.ok) {
      const err = await res.json().catch(() => ({})) as { error?: { message?: string } }
      throw new Error(err.error?.message ?? `OpenAI error ${res.status}`)
    }
    return res.arrayBuffer()
  }
  const voiceId = voice.trim() || ELEVENLABS_DEFAULT_VOICE
  const res = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`, {
    method: "POST",
    headers: { "xi-api-key": apiKey, "Content-Type": "application/json", Accept: "audio/mpeg" },
    body: JSON.stringify({ text, model_id: "eleven_multilingual_v2", voice_settings: { stability: 0.5, similarity_boost: 0.75 } }),
  })
  if (!res.ok) throw new Error(`ElevenLabs error ${res.status}`)
  return res.arrayBuffer()
}

// ── Styles ────────────────────────────────────────────────────────────────────

const S: Record<string, React.CSSProperties> = {
  page: {
    fontFamily: "system-ui, -apple-system, sans-serif",
    background: "linear-gradient(135deg,#0f0f23 0%,#1a1a3e 50%,#0d1117 100%)",
    minHeight: "100vh",
    color: "#e0e0ff",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "1.5rem",
    padding: "2rem",
  },
  h1: {
    fontSize: "2rem",
    fontWeight: 700,
    background: "linear-gradient(135deg,#a78bfa,#60a5fa)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    letterSpacing: "-0.5px",
  },
  subtitle:   { fontSize: "0.9rem", color: "#888", marginTop: "-1rem" },
  controls:   { display: "flex", flexDirection: "column", gap: "1rem", alignItems: "center", width: "100%", maxWidth: 680 },
  group:      { display: "flex", flexDirection: "column", gap: "0.4rem", alignItems: "center", width: "100%" },
  groupLabel: { fontSize: "0.65rem", textTransform: "uppercase" as const, letterSpacing: 1, color: "#666" },
  btnRow:     { display: "flex", gap: "0.4rem", flexWrap: "wrap" as const, justifyContent: "center" },
  btn: {
    padding: "0.45rem 0.9rem",
    border: "1px solid rgba(167,139,250,0.3)",
    borderRadius: 8,
    background: "rgba(167,139,250,0.08)",
    color: "#c4b5fd",
    fontSize: "0.8rem",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  btnActive: {
    padding: "0.45rem 0.9rem",
    border: "1px solid rgba(167,139,250,0.9)",
    borderRadius: 8,
    background: "rgba(167,139,250,0.3)",
    color: "#fff",
    fontSize: "0.8rem",
    cursor: "pointer",
  },
  divider:     { width: "100%", border: "none", borderTop: "1px solid rgba(167,139,250,0.1)" },
  inlineRow:   { display: "flex", gap: "1.5rem", flexWrap: "wrap" as const, justifyContent: "center", width: "100%" },
  configPanel: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem", width: "100%" },
  configBox:   { display: "flex", flexDirection: "column", gap: "0.5rem", padding: "0.75rem", border: "1px solid rgba(167,139,250,0.15)", borderRadius: 10, background: "rgba(167,139,250,0.04)" },
  sliderRow:   { display: "flex", alignItems: "center", gap: "0.5rem", fontSize: "0.75rem", color: "#aaa", width: "100%" },
  sliderLabel: { minWidth: "4rem", textAlign: "right" as const, color: "#888" },
  sliderVal:   { minWidth: "2.5rem", fontFamily: "monospace", color: "#c4b5fd" },
  colorRow:    { display: "flex", alignItems: "center", justifyContent: "center", gap: "0.5rem", fontSize: "0.75rem", color: "#888" },
  colorInput:  { width: "2.2rem", height: "1.5rem", cursor: "pointer", border: "1px solid rgba(167,139,250,0.3)", borderRadius: 4, background: "none", padding: 1 },
}

const sTTS: Record<string, React.CSSProperties> = {
  panel:    { display: "flex", flexDirection: "column", gap: "0.6rem", padding: "0.85rem 1rem", border: "1px solid rgba(96,165,250,0.25)", borderRadius: 12, background: "rgba(96,165,250,0.04)", width: "100%" },
  warning:  { fontSize: "0.68rem", color: "#f59e0b", background: "rgba(245,158,11,0.08)", border: "1px solid rgba(245,158,11,0.25)", borderRadius: 6, padding: "0.4rem 0.6rem", textAlign: "center" as const, lineHeight: 1.4 },
  row:      { display: "flex", gap: "0.5rem", alignItems: "center", width: "100%", flexWrap: "wrap" as const },
  label:    { fontSize: "0.72rem", color: "#888", minWidth: "4.5rem", textAlign: "right" as const },
  input:    { flex: 1, minWidth: 0, padding: "0.35rem 0.55rem", background: "rgba(255,255,255,0.05)", border: "1px solid rgba(167,139,250,0.2)", borderRadius: 6, color: "#e0e0ff", fontSize: "0.78rem" },
  textarea: { width: "100%", padding: "0.45rem 0.6rem", background: "rgba(255,255,255,0.05)", border: "1px solid rgba(167,139,250,0.2)", borderRadius: 6, color: "#e0e0ff", fontSize: "0.82rem", resize: "vertical" as const, minHeight: 56, fontFamily: "inherit" },
  speakBtn: { border: "1px solid rgba(96,165,250,0.4)", background: "rgba(96,165,250,0.1)", color: "#93c5fd", width: "100%", fontSize: "0.85rem", padding: "0.55rem", borderRadius: 8, cursor: "pointer" },
}

const FRAMINGS: AvatarFraming[] = ["full", "half", "bust", "face"]
const THEMES: AvatarTheme[]     = ["light", "dark", "transparent"]
const THEME_LABELS: Record<AvatarTheme, string> = { light: "☀️ light", dark: "🌙 dark", transparent: "◻️ transparent" }

// ── Component ─────────────────────────────────────────────────────────────────

export default function AvatarDemo() {
  const avatarRef = useAvatar({
    // Replace with any GLB/VRM URL hosted on a CORS-enabled CDN (e.g. Cloudflare R2,
    // GitHub Pages, or your own server). GitHub Releases URLs don't support CORS.
    // model: "https://cdn.jsdelivr.net/gh/mrdoob/three.js@r165/examples/models/gltf/RobotExpressive/RobotExpressive.glb",
    model: "/Maya.vrm",
    framing: INITIAL_FRAMING,
    position: "bottom-right",
    size: 400,
    theme: INITIAL_THEME,
    idle: true,
    idleInterval: 6000,
    blink: true,
    blinkInterval: 3000,
    lipSync: true,
    draggable: true,
    zIndex: 9999,
    framingConfig: FRAMING_CONFIG,
    themeConfig: {
      dark:  buildThemeCss("dark",  THEME_CONFIG),
      light: buildThemeCss("light", THEME_CONFIG),
    },
  })

  const [log, setLog]               = useState("Initializing…")
  const [logActive, setLogActive]   = useState(false)
  const [talking, setTalking]       = useState(false)
  const [activeFraming, setActiveFraming] = useState<AvatarFraming>(INITIAL_FRAMING)
  const [activeTheme, setActiveTheme]     = useState<AvatarTheme>(INITIAL_THEME)
  const [themeMode, setThemeMode]   = useState<ThemeMode>("dark")
  const [slices, setSlices]         = useState({ ...FRAMING_CONFIG })
  const [themeSlices, setThemeSlices] = useState<ThemeSlices>({ ...THEME_CONFIG })
  const [avatarSize, setAvatarSize]   = useState(400)
  const [ttsProvider, setTtsProvider] = useState("openai")
  const [ttsApiKey, setTtsApiKey]     = useState("")
  const [ttsVoice, setTtsVoice]       = useState("nova")
  const [ttsText, setTtsText]         = useState("Hello! I'm your Mymo avatar. How can I help you today?")
  const [ttsBusy, setTtsBusy]         = useState(false)
  const [ttsStatus, setTtsStatus]     = useState("")
  const [ttsStatusColor, setTtsStatusColor] = useState("#555")

  const flash = useCallback((msg: string) => {
    setLog(msg)
    setLogActive(true)
    setTimeout(() => setLogActive(false), 2000)
  }, [])

  useEffect(() => {
    const a = avatarRef.current
    if (!a) return
    a.on("loaded",         ()                      => flash("Avatar loaded ✓"))
    a.on("modelLoaded",    ()                      => flash("Model ready ✓"))
    a.on("click",          ()                      => { a.wave(); flash("avatar.wave()") })
    a.on("animationStart", (_: string, d: unknown) => flash(`animationStart: ${JSON.stringify(d)}`))
    a.on("speechStart",    ()                      => { setLog("speechStart — talking…"); setLogActive(false); setTalking(true) })
    a.on("speechEnd",      ()                      => { flash("speechEnd ✓"); setTalking(false) })
  }, [flash]) // eslint-disable-line react-hooks/exhaustive-deps

  const av = () => avatarRef.current!

  function act(label: string, fn: () => void) {
    flash(`avatar.${label}()`)
    fn()
  }

  function selectFraming(mode: AvatarFraming) {
    setActiveFraming(mode)
    av().frame(mode)
    flash(`avatar.frame("${mode}")`)
  }

  function selectTheme(theme: AvatarTheme) {
    setActiveTheme(theme)
    if (theme !== "transparent") setThemeMode(theme)
    av().setTheme(theme)
    flash(`avatar.setTheme("${theme}")`)
  }

  function updateSlice(mode: AvatarFraming, key: "from" | "lookBias", value: number) {
    setSlices(prev => {
      const next = { ...prev, [mode]: { ...prev[mode], [key]: value } }
      avatarRef.current?.setFramingConfig({ [mode]: next[mode] })
      flash(`framingConfig.${mode}.${key} = ${value.toFixed(2)}`)
      return next
    })
  }

  function updateThemeSlice(mode: ThemeMode, key: keyof ThemeSlices[ThemeMode], value: string | number) {
    setThemeSlices(prev => {
      const next = { ...prev, [mode]: { ...prev[mode], [key]: value } } as ThemeSlices
      avatarRef.current?.setThemeConfig({ [mode]: buildThemeCss(mode, next) })
      flash(`themeConfig.${mode}.${key} updated`)
      return next
    })
  }

  function updateSize(px: number) {
    setAvatarSize(px)
    av().size(px)
    flash(`avatar.size(${px})`)
  }

  async function handleSpeak() {
    const text = ttsText.trim()
    if (!text) return
    setTtsBusy(true)
    setTtsStatus("Generating audio…")
    setTtsStatusColor("#60a5fa")
    try {
      const audio = await fetchTTSAudio(ttsProvider, ttsApiKey, ttsVoice, text)
      setTtsStatus("Playing…")
      await av().talk(audio)
      setTtsStatus("Done ✓")
      setTtsStatusColor("#a78bfa")
      setTimeout(() => setTtsStatus(""), 2000)
    } catch (err) {
      setTtsStatus(`Error: ${err instanceof Error ? err.message : String(err)}`)
      setTtsStatusColor("#f87171")
    } finally {
      setTtsBusy(false)
    }
  }

  const cfg      = slices[activeFraming]
  const themeCfg = themeSlices[themeMode]

  function group(label: string, children: React.ReactNode) {
    return (
      <div style={{ ...S.group, width: "auto" }}>
        <span style={S.groupLabel}>{label}</span>
        <div style={S.btnRow}>{children}</div>
      </div>
    )
  }

  function btn(label: string, fn: () => void, display?: string) {
    return <button key={label} style={S.btn} onClick={() => act(label, fn)}>{display ?? label}</button>
  }

  return (
    <div style={S.page}>
      <h1 style={S.h1}>Mymo Avatar — Next.js</h1>
      <p style={S.subtitle}>SDK Demo — App Router + dynamic import (ssr: false)</p>

      <div style={S.controls}>

        {/* Expressions */}
        <div style={S.group}>
          <span style={S.groupLabel}>Expressions</span>
          <div style={S.btnRow}>
            {btn("smile",     () => av().smile(),     "😊 smile")}
            {btn("happy",     () => av().happy(),     "😄 happy")}
            {btn("sad",       () => av().sad(),       "😢 sad")}
            {btn("angry",     () => av().angry(),     "😠 angry")}
            {btn("surprised", () => av().surprised(), "😲 surprised")}
            {btn("thinking",  () => av().thinking(),  "🤔 thinking")}
            {btn("confused",  () => av().confused(),  "😕 confused")}
            {btn("sleep",     () => av().sleep(),     "😴 sleep")}
            {btn("idle",      () => av().idle(),      "😐 idle")}
          </div>
        </div>

        <hr style={S.divider} />

        {/* Gestures */}
        <div style={S.group}>
          <span style={S.groupLabel}>Gestures</span>
          <div style={S.btnRow}>
            {btn("wave",      () => av().wave(),      "👋 wave")}
            {btn("nod",       () => av().nod(),       "↕️ nod")}
            {btn("yes",       () => av().yes(),       "✅ yes")}
            {btn("no",        () => av().no(),        "❌ no")}
            {btn("shakeHead", () => av().shakeHead(), "🙅 shakeHead")}
            {btn("clap",      () => av().clap(),      "👏 clap")}
            {btn("jump",      () => av().jump(),      "⬆️ jump")}
            {btn("dance",     () => av().dance(),     "💃 dance")}
            {btn("thumbsUp",  () => av().thumbsUp(),  "👍 thumbsUp")}
          </div>
        </div>

        <hr style={S.divider} />

        {/* States */}
        <div style={S.group}>
          <span style={S.groupLabel}>States</span>
          <div style={S.btnRow}>
            {btn("loading",    () => av().loading(),    "⏳ loading")}
            {btn("success",    () => av().success(),    "✅ success")}
            {btn("error",      () => av().error(),      "❌ error")}
            {btn("warning",    () => av().warning(),    "⚠️ warning")}
            {btn("listening",  () => av().listening(),  "👂 listening")}
            {btn("typing",     () => av().typing(),     "⌨️ typing")}
            {btn("processing", () => av().processing(), "⚙️ processing")}
            {btn("complete",   () => av().complete(),   "🏁 complete")}
            {btn("clearState", () => av().clearState(), "✖ clear")}
          </div>
        </div>

        <hr style={S.divider} />

        {/* Look · Speech · Position */}
        <div style={S.inlineRow}>
          {group("Look", <>
            {btn("lookAtMouse", () => av().lookAtMouse(), "👁️ follow mouse")}
            {btn("lookForward", () => av().lookForward(), "⬛ look forward")}
            {btn("randomLook",  () => av().randomLook(),  "🔀 random look")}
          </>)}
          {group("Speech", <>
            {btn("talk",        () => loadDemoAudio().then(buf => av().talk(buf)).catch(console.error), "🗣️ talk")}
            {btn("stopTalking", () => av().stopTalking(), "🔇 stop")}
          </>)}
          {group("Position", <>
            {btn("bottom-right", () => av().position("bottom-right" as AvatarPosition), "↘ bottom-right")}
            {btn("bottom-left",  () => av().position("bottom-left"  as AvatarPosition), "↙ bottom-left")}
            {btn("top-right",    () => av().position("top-right"    as AvatarPosition), "↗ top-right")}
            {btn("top-left",     () => av().position("top-left"     as AvatarPosition), "↖ top-left")}
          </>)}
        </div>

        <hr style={S.divider} />

        {/* Size */}
        <div style={S.group}>
          <span style={S.groupLabel}>Size</span>
          <div style={{ ...S.sliderRow, maxWidth: 340, width: "100%" }}>
            <label style={S.sliderLabel}>px</label>
            <input type="range" min={80} max={600} step={10} value={avatarSize}
              style={{ flex: 1, accentColor: "#a78bfa" }}
              onChange={e => updateSize(parseInt(e.target.value, 10))} />
            <span style={S.sliderVal}>{avatarSize}</span>
          </div>
        </div>

        <hr style={S.divider} />

        {/* Framing + Theme config panel */}
        <div style={S.configPanel}>

          {/* Framing */}
          <div style={S.configBox}>
            <span style={{ ...S.groupLabel, alignSelf: "center" }}>Framing — {activeFraming}</span>
            <div style={S.btnRow}>
              {FRAMINGS.map(m => (
                <button key={m} style={activeFraming === m ? S.btnActive : S.btn} onClick={() => selectFraming(m)}>{m}</button>
              ))}
            </div>
            <div style={S.sliderRow}>
              <label style={S.sliderLabel}>from</label>
              <input type="range" min={0} max={1} step={0.01} value={cfg.from}
                style={{ flex: 1, accentColor: "#a78bfa" }}
                onChange={e => updateSlice(activeFraming, "from", parseFloat(e.target.value))} />
              <span style={S.sliderVal}>{cfg.from.toFixed(2)}</span>
            </div>
            <div style={S.sliderRow}>
              <label style={S.sliderLabel}>lookBias</label>
              <input type="range" min={0} max={1} step={0.01} value={cfg.lookBias}
                style={{ flex: 1, accentColor: "#a78bfa" }}
                onChange={e => updateSlice(activeFraming, "lookBias", parseFloat(e.target.value))} />
              <span style={S.sliderVal}>{cfg.lookBias.toFixed(2)}</span>
            </div>
          </div>

          {/* Theme */}
          <div style={S.configBox}>
            <span style={{ ...S.groupLabel, alignSelf: "center" }}>Theme</span>
            <div style={S.btnRow}>
              {THEMES.map(t => (
                <button key={t} style={activeTheme === t ? S.btnActive : S.btn} onClick={() => selectTheme(t)}>{THEME_LABELS[t]}</button>
              ))}
            </div>
            {activeTheme !== "transparent" && <>
              <div style={S.colorRow}>
                <label>center</label>
                <input type="color" value={themeCfg.color1} style={S.colorInput}
                  onChange={e => updateThemeSlice(themeMode, "color1", e.target.value)} />
                <label>edge</label>
                <input type="color" value={themeCfg.color2} style={S.colorInput}
                  onChange={e => updateThemeSlice(themeMode, "color2", e.target.value)} />
              </div>
              <div style={S.sliderRow}>
                <label style={S.sliderLabel}>shadow</label>
                <input type="range" min={0} max={1} step={0.05} value={themeCfg.shadowOpacity}
                  style={{ flex: 1, accentColor: "#a78bfa" }}
                  onChange={e => updateThemeSlice(themeMode, "shadowOpacity", parseFloat(e.target.value))} />
                <span style={S.sliderVal}>{themeCfg.shadowOpacity.toFixed(2)}</span>
              </div>
            </>}
          </div>

        </div>

        <hr style={S.divider} />

        {/* TTS Demo */}
        <div style={sTTS.panel}>
          <span style={{ ...S.groupLabel, color: "#60a5fa" }}>TTS Demo — speak with AI</span>
          <p style={sTTS.warning}>
            ⚠️ For testing only — paste your key to try TTS directly from the browser.<br />
            Never ship API keys in frontend code. Use a backend proxy in production.
          </p>
          <div style={sTTS.row}>
            <label style={sTTS.label}>Provider</label>
            <select value={ttsProvider} onChange={e => { setTtsProvider(e.target.value); setTtsVoice(e.target.value === "openai" ? "nova" : "") }} style={sTTS.input}>
              <option value="openai">OpenAI TTS</option>
              <option value="elevenlabs">ElevenLabs</option>
            </select>
          </div>
          <div style={sTTS.row}>
            <label style={sTTS.label}>API Key</label>
            <input type="password" value={ttsApiKey} onChange={e => setTtsApiKey(e.target.value)}
              placeholder={ttsProvider === "openai" ? "sk-…" : "Your ElevenLabs API key"}
              style={sTTS.input} autoComplete="off" />
          </div>
          <div style={sTTS.row}>
            <label style={sTTS.label}>Voice</label>
            {ttsProvider === "openai"
              ? <select value={ttsVoice} onChange={e => setTtsVoice(e.target.value)} style={sTTS.input}>
                  {["alloy","echo","fable","nova","onyx","shimmer"].map(v => <option key={v} value={v}>{v}</option>)}
                </select>
              : <input type="text" value={ttsVoice} onChange={e => setTtsVoice(e.target.value)}
                  placeholder="Voice ID (e.g. 21m00Tcm4TlvDq8ikWAM)" style={sTTS.input} />
            }
          </div>
          <textarea value={ttsText} onChange={e => setTtsText(e.target.value)}
            placeholder="Type something for the avatar to say…" style={sTTS.textarea} />
          <button onClick={handleSpeak} disabled={ttsBusy} style={sTTS.speakBtn}>🔊 Speak</button>
          <div style={{ fontSize: "0.72rem", fontFamily: "monospace", textAlign: "center", minHeight: "1rem", color: ttsStatusColor }}>{ttsStatus}</div>
        </div>

      </div>

      {talking && (
        <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", width: 260 }}>
          <span style={{ fontSize: "0.7rem", color: "#a78bfa" }}>🎙️ talking</span>
          <div style={{ flex: 1, height: 6, background: "rgba(255,255,255,0.08)", borderRadius: 3, overflow: "hidden" }}>
            <div style={{ height: "100%", width: "60%", background: "linear-gradient(90deg,#a78bfa,#60a5fa)", borderRadius: 3 }} />
          </div>
        </div>
      )}

      <div style={{ fontSize: "0.75rem", color: logActive ? "#a78bfa" : "#555", fontFamily: "monospace", height: "1.2rem", transition: "color 0.3s" }}>
        {log}
      </div>
    </div>
  )
}

// examples/nuxt/components/AvatarDemo.vue
<script setup lang="ts">
import { ref, reactive, computed, onMounted, onUnmounted } from "vue"
import { Avatar } from "@mymosdk/avatar"
import type { AvatarPosition, AvatarFraming, AvatarTheme } from "@mymosdk/avatar"

const MODEL = "/Maya.vrm"
const INITIAL_FRAMING: AvatarFraming = "full"
const INITIAL_THEME: AvatarTheme = "dark"

const FRAMING_CONFIG = {
  full: { from: 0.00, lookBias: 0.50 },
  half: { from: 0.48, lookBias: 0.60 },
  bust: { from: 0.60, lookBias: 0.70 },
  face: { from: 0.76, lookBias: 0.58 },
}
const THEME_CONFIG = {
  dark:  { background: "radial-gradient(circle at 40% 35%, #2a2a4a 0%, #0d0d1a 100%)", boxShadow: "0 8px 32px rgba(0,0,0,0.5), 0 0 0 2px rgba(255,255,255,0.08)" },
  light: { background: "radial-gradient(circle at 40% 35%, #f8f8ff 0%, #e0e0f0 100%)", boxShadow: "0 8px 32px rgba(0,0,0,0.15), 0 0 0 2px rgba(0,0,0,0.06)" },
}

let avatar: Avatar
let ampRAF = 0
let logTimer: ReturnType<typeof setTimeout>

const logMsg      = ref("Initializing avatar...")
const logActive   = ref(false)
const talkingVisible = ref(false)
const sizeValue   = ref(400)
const activeFraming = ref<string>(INITIAL_FRAMING)
const activeTheme   = ref<string>(INITIAL_THEME)
const showTcPanel   = ref(true)
const currentThemeMode = ref<"dark" | "light">(INITIAL_THEME as "dark" | "light")

const framingSlices = reactive({
  full: { ...FRAMING_CONFIG.full },
  half: { ...FRAMING_CONFIG.half },
  bust: { ...FRAMING_CONFIG.bust },
  face: { ...FRAMING_CONFIG.face },
})
const themeSlices = reactive({
  dark:  { color1: "#2a2a4a", color2: "#0d0d1a", shadowOpacity: 0.5  },
  light: { color1: "#f8f8ff", color2: "#e0e0f0", shadowOpacity: 0.15 },
})

const fcCurrent = computed(() => framingSlices[activeFraming.value as keyof typeof framingSlices])
const tcCurrent = computed(() => themeSlices[currentThemeMode.value])

function setLog(msg: string, active = false) {
  logMsg.value    = msg
  logActive.value = active
  if (active) {
    clearTimeout(logTimer)
    logTimer = setTimeout(() => { logActive.value = false }, 2000)
  }
}

function buildThemeConfig(mode: "dark" | "light") {
  const { color1, color2, shadowOpacity } = themeSlices[mode]
  const ringOpacity = mode === "dark" ? 0.08 : 0.06
  const ringColor   = mode === "dark" ? "255,255,255" : "0,0,0"
  return {
    background: `radial-gradient(circle at 40% 35%, ${color1} 0%, ${color2} 100%)`,
    boxShadow:  `0 8px 32px rgba(0,0,0,${shadowOpacity}), 0 0 0 2px rgba(${ringColor},${ringOpacity})`,
  }
}

async function loadDemoAudio(): Promise<AudioBuffer> {
  const ctx = new AudioContext()
  const res = await fetch("/demo_voice_example.mp3")
  return ctx.decodeAudioData(await res.arrayBuffer())
}

function startAmpViz() {
  const tick = () => { ampRAF = requestAnimationFrame(tick) }
  tick()
}
function stopAmpViz() { cancelAnimationFrame(ampRAF) }

const ACTIONS: Record<string, () => void> = {
  smile:     () => avatar.smile(),
  happy:     () => avatar.happy(),
  sad:       () => avatar.sad(),
  angry:     () => avatar.angry(),
  surprised: () => avatar.surprised(),
  thinking:  () => avatar.thinking(),
  confused:  () => avatar.confused(),
  sleep:     () => avatar.sleep(),
  idle:      () => avatar.idle(),
  wave:      () => avatar.wave(),
  nod:       () => avatar.nod(),
  yes:       () => avatar.yes(),
  no:        () => avatar.no(),
  shakeHead: () => avatar.shakeHead(),
  clap:      () => avatar.clap(),
  jump:      () => avatar.jump(),
  dance:     () => avatar.dance(),
  thumbsUp:  () => avatar.thumbsUp(),
  loading:    () => avatar.loading(),
  success:    () => avatar.success(),
  error:      () => avatar.error(),
  warning:    () => avatar.warning(),
  listening:  () => avatar.listening(),
  typing:     () => avatar.typing(),
  processing: () => avatar.processing(),
  complete:   () => avatar.complete(),
  clearState: () => avatar.clearState(),
  lookAtMouse:  () => avatar.lookAtMouse(),
  lookForward:  () => avatar.lookForward(),
  randomLook:   () => avatar.randomLook(),
  talk:         () => loadDemoAudio().then(b => avatar.talk(b)).catch(console.error),
  stopTalking:  () => avatar.stopTalking(),
  "pos-bottom-right": () => avatar.position("bottom-right" as AvatarPosition),
  "pos-bottom-left":  () => avatar.position("bottom-left"  as AvatarPosition),
  "pos-top-right":    () => avatar.position("top-right"    as AvatarPosition),
  "pos-top-left":     () => avatar.position("top-left"     as AvatarPosition),
}

function doAction(action: string) {
  setLog(`avatar.${action}()`, true)
  ACTIONS[action]?.()
}

function doFrame(framing: AvatarFraming) {
  activeFraming.value = framing
  avatar?.frame(framing)
  setLog(`avatar.frame("${framing}")`, true)
}

function doTheme(theme: AvatarTheme) {
  activeTheme.value = theme
  avatar?.setTheme(theme)
  if (theme === "transparent") {
    showTcPanel.value = false
  } else {
    currentThemeMode.value = theme as "dark" | "light"
    showTcPanel.value = true
  }
  setLog(`avatar.setTheme("${theme}")`, true)
}

function onSizeInput(e: Event) {
  const px = parseInt((e.target as HTMLInputElement).value, 10)
  sizeValue.value = px
  avatar?.size(px)
  setLog(`avatar.size(${px})`, true)
}

// ── TTS Demo ──────────────────────────────────────────────────────────────────

const ELEVENLABS_DEFAULT_VOICE = "21m00Tcm4TlvDq8ikWAM"

const ttsProvider = ref("openai")
const ttsApiKey   = ref("")
const ttsVoice    = ref("nova")
const ttsText     = ref("Hello! I'm your Mymo avatar. How can I help you today?")
const ttsBusy     = ref(false)
const ttsStatus   = ref("")
const ttsStatusColor = ref("#555")

function onTtsProviderChange(e: Event) {
  ttsProvider.value = (e.target as HTMLSelectElement).value
  ttsVoice.value = ttsProvider.value === "openai" ? "nova" : ""
}

async function fetchTTSAudio(provider: string, apiKey: string, voice: string, text: string): Promise<ArrayBuffer> {
  if (!apiKey.trim()) throw new Error("Paste your API key first")
  if (provider === "openai") {
    const res = await fetch("https://api.openai.com/v1/audio/speech", {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({ model: "tts-1", voice, input: text }),
    })
    if (!res.ok) {
      const err = await res.json().catch(() => ({})) as { error?: { message?: string } }
      throw new Error(err.error?.message ?? `OpenAI error ${res.status}`)
    }
    return res.arrayBuffer()
  }
  const voiceId = voice.trim() || ELEVENLABS_DEFAULT_VOICE
  const res = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`, {
    method: "POST",
    headers: { "xi-api-key": apiKey, "Content-Type": "application/json", Accept: "audio/mpeg" },
    body: JSON.stringify({ text, model_id: "eleven_multilingual_v2", voice_settings: { stability: 0.5, similarity_boost: 0.75 } }),
  })
  if (!res.ok) throw new Error(`ElevenLabs error ${res.status}`)
  return res.arrayBuffer()
}

async function handleSpeak() {
  const text = ttsText.value.trim()
  if (!text) return
  ttsBusy.value = true
  ttsStatus.value = "Generating audio…"
  ttsStatusColor.value = "#60a5fa"
  try {
    const audio = await fetchTTSAudio(ttsProvider.value, ttsApiKey.value, ttsVoice.value, text)
    ttsStatus.value = "Playing…"
    await avatar.talk(audio)
    ttsStatus.value = "Done ✓"
    ttsStatusColor.value = "#a78bfa"
    setTimeout(() => { ttsStatus.value = "" }, 2000)
  } catch (err) {
    ttsStatus.value = `Error: ${err instanceof Error ? err.message : String(err)}`
    ttsStatusColor.value = "#f87171"
  } finally {
    ttsBusy.value = false
  }
}

function onFcFromInput(e: Event) {
  const v = parseFloat((e.target as HTMLInputElement).value)
  framingSlices[activeFraming.value as keyof typeof framingSlices].from = v
  avatar?.setFramingConfig({ [activeFraming.value]: framingSlices[activeFraming.value as keyof typeof framingSlices] })
  setLog(`framingConfig.${activeFraming.value}.from = ${v.toFixed(2)}`, true)
}

function onFcBiasInput(e: Event) {
  const v = parseFloat((e.target as HTMLInputElement).value)
  framingSlices[activeFraming.value as keyof typeof framingSlices].lookBias = v
  avatar?.setFramingConfig({ [activeFraming.value]: framingSlices[activeFraming.value as keyof typeof framingSlices] })
  setLog(`framingConfig.${activeFraming.value}.lookBias = ${v.toFixed(2)}`, true)
}

function onTcColor1Input(e: Event) {
  const v = (e.target as HTMLInputElement).value
  themeSlices[currentThemeMode.value].color1 = v
  avatar?.setThemeConfig({ [currentThemeMode.value]: buildThemeConfig(currentThemeMode.value) })
  setLog(`themeConfig.${currentThemeMode.value}.center = ${v}`, true)
}

function onTcColor2Input(e: Event) {
  const v = (e.target as HTMLInputElement).value
  themeSlices[currentThemeMode.value].color2 = v
  avatar?.setThemeConfig({ [currentThemeMode.value]: buildThemeConfig(currentThemeMode.value) })
  setLog(`themeConfig.${currentThemeMode.value}.edge = ${v}`, true)
}

function onTcShadowInput(e: Event) {
  const v = parseFloat((e.target as HTMLInputElement).value)
  themeSlices[currentThemeMode.value].shadowOpacity = v
  avatar?.setThemeConfig({ [currentThemeMode.value]: buildThemeConfig(currentThemeMode.value) })
  setLog(`themeConfig.${currentThemeMode.value}.shadow = ${v.toFixed(2)}`, true)
}

onMounted(() => {
  avatar = new Avatar({
    model: MODEL,
    framing: INITIAL_FRAMING,
    position: "bottom-right",
    size: 400,
    theme: INITIAL_THEME,
    idle: true,
    idleInterval: 6000,
    blink: true,
    blinkInterval: 3000,
    lipSync: true,
    draggable: true,
    zIndex: 9999,
    framingConfig: FRAMING_CONFIG,
    themeConfig: THEME_CONFIG,
  })

  avatar
    .on("loaded",         ()         => setLog("Avatar loaded ✓", true))
    .on("modelLoaded",    ()         => setLog("Model ready ✓", true))
    .on("click",          ()         => { avatar.wave(); setLog("avatar.wave()", true) })
    .on("animationStart", (_, data)  => setLog(`animationStart: ${JSON.stringify(data)}`, true))
    .on("speechStart",    ()         => { setLog("speechStart — talking…"); talkingVisible.value = true;  startAmpViz() })
    .on("speechEnd",      ()         => { setLog("speechEnd ✓", true);       talkingVisible.value = false; stopAmpViz()  })
})

onUnmounted(() => {
  avatar?.destroy()
  cancelAnimationFrame(ampRAF)
  clearTimeout(logTimer)
})
</script>

<template>
  <h1>Mymo Avatar</h1>
  <p class="subtitle">SDK Demo — lightweight animated avatar</p>

  <div class="controls">

    <div class="group">
      <span class="group-label">Expressions</span>
      <div class="btn-row">
        <button v-for="a in ['smile','happy','sad','angry','surprised','thinking','confused','sleep','idle']"
                :key="a" @click="doAction(a)">{{ a }}</button>
      </div>
    </div>

    <hr class="divider">

    <div class="group">
      <span class="group-label">Gestures</span>
      <div class="btn-row">
        <button v-for="a in ['wave','nod','yes','no','shakeHead','clap','jump','dance','thumbsUp']"
                :key="a" @click="doAction(a)">{{ a }}</button>
      </div>
    </div>

    <hr class="divider">

    <div class="group">
      <span class="group-label">States</span>
      <div class="btn-row">
        <button v-for="a in ['loading','success','error','warning','listening','typing','processing','complete','clearState']"
                :key="a" @click="doAction(a)">{{ a }}</button>
      </div>
    </div>

    <hr class="divider">

    <div class="inline-groups">
      <div class="group">
        <span class="group-label">Look</span>
        <div class="btn-row">
          <button @click="doAction('lookAtMouse')">follow mouse</button>
          <button @click="doAction('lookForward')">look forward</button>
          <button @click="doAction('randomLook')">random look</button>
        </div>
      </div>

      <div class="group">
        <span class="group-label">Speech</span>
        <div class="btn-row">
          <button @click="doAction('talk')">talk</button>
          <button @click="doAction('stopTalking')">stop</button>
        </div>
      </div>

      <div class="group">
        <span class="group-label">Position</span>
        <div class="btn-row">
          <button v-for="pos in ['bottom-right','bottom-left','top-right','top-left']"
                  :key="pos" @click="doAction(`pos-${pos}`)">{{ pos }}</button>
        </div>
      </div>
    </div>

    <hr class="divider">

    <div class="group">
      <span class="group-label">Size</span>
      <div class="slider-row" style="max-width:340px; width:100%;">
        <label>px</label>
        <input type="range" min="80" max="600" step="10" :value="sizeValue" @input="onSizeInput">
        <span class="val">{{ sizeValue }}</span>
      </div>
    </div>

    <hr class="divider">

    <div class="config-panel">

      <div class="config-box">
        <span class="group-label">Framing — <span>{{ activeFraming }}</span></span>
        <div class="btn-row">
          <button v-for="f in ['full','half','bust','face']" :key="f"
                  :class="{ active: activeFraming === f }" @click="doFrame(f as AvatarFraming)">{{ f }}</button>
        </div>
        <div class="slider-row">
          <label>from</label>
          <input type="range" min="0" max="1" step="0.01" :value="fcCurrent.from" @input="onFcFromInput">
          <span class="val">{{ fcCurrent.from.toFixed(2) }}</span>
        </div>
        <div class="slider-row">
          <label>lookBias</label>
          <input type="range" min="0" max="1" step="0.01" :value="fcCurrent.lookBias" @input="onFcBiasInput">
          <span class="val">{{ fcCurrent.lookBias.toFixed(2) }}</span>
        </div>
      </div>

      <div class="config-box">
        <span class="group-label">Theme</span>
        <div class="btn-row">
          <button v-for="t in ['light','dark','transparent']" :key="t"
                  :class="{ active: activeTheme === t }" @click="doTheme(t as AvatarTheme)">{{ t }}</button>
        </div>

        <template v-if="showTcPanel">
          <div class="color-row">
            <label>center</label>
            <input type="color" :value="tcCurrent.color1" @input="onTcColor1Input">
            <label>edge</label>
            <input type="color" :value="tcCurrent.color2" @input="onTcColor2Input">
          </div>
          <div class="slider-row">
            <label>shadow</label>
            <input type="range" min="0" max="1" step="0.05" :value="tcCurrent.shadowOpacity" @input="onTcShadowInput">
            <span class="val">{{ tcCurrent.shadowOpacity.toFixed(2) }}</span>
          </div>
        </template>
      </div>

      <hr class="divider">

      <!-- TTS Demo -->
      <div class="tts-panel">
        <span class="group-label tts-label">TTS Demo — speak with AI</span>
        <p class="tts-warning">
          ⚠️ For testing only — paste your key to try TTS directly from the browser.<br>
          Never ship API keys in frontend code. Use a backend proxy in production.
        </p>
        <div class="tts-row">
          <label class="tts-field-label">Provider</label>
          <select :value="ttsProvider" @change="onTtsProviderChange" class="tts-input">
            <option value="openai">OpenAI TTS</option>
            <option value="elevenlabs">ElevenLabs</option>
          </select>
        </div>
        <div class="tts-row">
          <label class="tts-field-label">API Key</label>
          <input type="password" :value="ttsApiKey" @input="ttsApiKey = ($event.target as HTMLInputElement).value"
            :placeholder="ttsProvider === 'openai' ? 'sk-…' : 'Your ElevenLabs API key'"
            class="tts-input" autocomplete="off" />
        </div>
        <div class="tts-row">
          <label class="tts-field-label">Voice</label>
          <select v-if="ttsProvider === 'openai'" :value="ttsVoice" @change="ttsVoice = ($event.target as HTMLSelectElement).value" class="tts-input">
            <option v-for="v in ['alloy','echo','fable','nova','onyx','shimmer']" :key="v" :value="v">{{ v }}</option>
          </select>
          <input v-else type="text" :value="ttsVoice" @input="ttsVoice = ($event.target as HTMLInputElement).value"
            placeholder="Voice ID (e.g. 21m00Tcm4TlvDq8ikWAM)" class="tts-input" />
        </div>
        <textarea :value="ttsText" @input="ttsText = ($event.target as HTMLTextAreaElement).value"
          placeholder="Type something for the avatar to say…" class="tts-textarea" />
        <button @click="handleSpeak" :disabled="ttsBusy" class="tts-speak-btn">🔊 Speak</button>
        <div class="tts-status" :style="{ color: ttsStatusColor }">{{ ttsStatus }}</div>
      </div>

    </div>
  </div>

  <div v-if="talkingVisible" style="display:flex; align-items:center; gap:0.5rem; width:260px;">
    <span style="font-size:0.7rem; color:#a78bfa;">🎙️ talking</span>
    <div style="flex:1; height:6px; background:rgba(255,255,255,0.08); border-radius:3px; overflow:hidden;">
      <div style="height:100%; width:30%; background:linear-gradient(90deg,#a78bfa,#60a5fa); border-radius:3px; transition:width 0.05s ease;"></div>
    </div>
  </div>

  <div id="log" :class="{ active: logActive }">{{ logMsg }}</div>
</template>

<style scoped>
h1 {
  font-size: 2rem; font-weight: 700;
  background: linear-gradient(135deg, #a78bfa, #60a5fa);
  -webkit-background-clip: text; -webkit-text-fill-color: transparent;
  letter-spacing: -0.5px;
}
.subtitle { font-size: 0.9rem; color: #888; margin-top: -1rem; }

.controls { display: flex; flex-direction: column; gap: 1rem; align-items: center; width: 100%; max-width: 680px; }
.group { display: flex; flex-direction: column; gap: 0.4rem; align-items: center; width: 100%; }
.group-label { font-size: 0.65rem; text-transform: uppercase; letter-spacing: 1px; color: #666; }
.btn-row { display: flex; gap: 0.4rem; flex-wrap: wrap; justify-content: center; }

button {
  padding: 0.45rem 0.9rem;
  border: 1px solid rgba(167, 139, 250, 0.3); border-radius: 8px;
  background: rgba(167, 139, 250, 0.08); color: #c4b5fd;
  font-size: 0.8rem; cursor: pointer; transition: all 0.15s ease;
}
button:hover { background: rgba(167, 139, 250, 0.2); border-color: rgba(167, 139, 250, 0.6); color: #fff; }
button:active { transform: scale(0.96); }
button.active { background: rgba(167, 139, 250, 0.3); border-color: rgba(167, 139, 250, 0.9); color: #fff; }

.divider { width: 100%; border: none; border-top: 1px solid rgba(167, 139, 250, 0.1); }

.inline-groups { display: flex; gap: 1.5rem; flex-wrap: wrap; justify-content: center; width: 100%; }
.inline-groups .group { width: auto; align-items: center; }

.config-panel { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; width: 100%; }
.config-box {
  display: flex; flex-direction: column; gap: 0.5rem; padding: 0.75rem;
  border: 1px solid rgba(167, 139, 250, 0.15); border-radius: 10px;
  background: rgba(167, 139, 250, 0.04);
}

.slider-row { display: flex; align-items: center; gap: 0.5rem; font-size: 0.75rem; color: #aaa; width: 100%; }
.slider-row label { min-width: 4rem; text-align: right; color: #888; }
.slider-row input[type="range"] { flex: 1; accent-color: #a78bfa; cursor: pointer; }
.slider-row .val { min-width: 2.5rem; font-family: monospace; color: #c4b5fd; }

.color-row { display: flex; align-items: center; justify-content: center; gap: 0.5rem; font-size: 0.75rem; color: #888; }
input[type="color"] {
  width: 2.2rem; height: 1.5rem; cursor: pointer;
  border: 1px solid rgba(167,139,250,0.3); border-radius: 4px;
  background: none; padding: 1px;
}

#log { font-size: 0.75rem; color: #555; font-family: monospace; height: 1.2rem; transition: color 0.3s; }
#log.active { color: #a78bfa; }

.tts-panel {
  display: flex; flex-direction: column; gap: 0.6rem;
  padding: 0.85rem 1rem;
  border: 1px solid rgba(96,165,250,0.25); border-radius: 12px;
  background: rgba(96,165,250,0.04); width: 100%;
}
.tts-label { color: #60a5fa; }
.tts-warning {
  font-size: 0.68rem; color: #f59e0b;
  background: rgba(245,158,11,0.08); border: 1px solid rgba(245,158,11,0.25);
  border-radius: 6px; padding: 0.4rem 0.6rem; text-align: center; line-height: 1.4;
}
.tts-row { display: flex; gap: 0.5rem; align-items: center; width: 100%; flex-wrap: wrap; }
.tts-field-label { font-size: 0.72rem; color: #888; min-width: 4.5rem; text-align: right; }
.tts-input {
  flex: 1; min-width: 0; padding: 0.35rem 0.55rem;
  background: rgba(255,255,255,0.05); border: 1px solid rgba(167,139,250,0.2);
  border-radius: 6px; color: #e0e0ff; font-size: 0.78rem;
}
.tts-input option { background: #1a1a3e; }
.tts-textarea {
  width: 100%; padding: 0.45rem 0.6rem;
  background: rgba(255,255,255,0.05); border: 1px solid rgba(167,139,250,0.2);
  border-radius: 6px; color: #e0e0ff; font-size: 0.82rem;
  resize: vertical; min-height: 56px; font-family: inherit;
}
.tts-speak-btn {
  border: 1px solid rgba(96,165,250,0.4) !important;
  background: rgba(96,165,250,0.1) !important;
  color: #93c5fd !important; width: 100%; font-size: 0.85rem; padding: 0.55rem;
}
.tts-speak-btn:disabled { opacity: 0.4; cursor: not-allowed; transform: none; }
.tts-status { font-size: 0.72rem; font-family: monospace; text-align: center; min-height: 1rem; }
</style>
